In [1]:
!pip install numpy

In [2]:
!pip install pandas

In [3]:
import numpy as np
import pandas as pd

In [4]:
# In numpy, we have
#--------------------
# 1. Numpy n-D array



# In pandas
#-----------------
# 1. Series (1-D Data/Single Column)
# 2. DataFrame (2-D Data/ MultiColumn/ Tabular)
# 3. Panel (3D Data/Multi-table)

In [6]:
a = np.array([])
a

array([], dtype=float64)

In [10]:
print(a)

[]


In [11]:
type(a)

numpy.ndarray

In [12]:
a.dtype

dtype('float64')

In [13]:
a.astype(int)

array([], dtype=int32)

In [14]:
len(a)

0

In [15]:
a.shape

(0,)

In [16]:
a.size

0

In [17]:
a.ndim

1

In [7]:
a1 = np.array([4,6,87,2])
a1

array([ 4,  6, 87,  2])

In [18]:
len(a1)

4

In [19]:
type(a1)

numpy.ndarray

In [20]:
print(a1)

[ 4  6 87  2]


In [21]:
a1.shape

(4,)

In [22]:
a1.size

4

In [23]:
a1.ndim

1

In [25]:
a1.dtype

dtype('int32')

In [8]:
a2 = np.array([[4,6],[87,2]])
a2

array([[ 4,  6],
       [87,  2]])

In [26]:
a2.shape

(2, 2)

In [27]:
a2.size

4

In [28]:
len(a2)

2

In [29]:
a2.ndim

2

In [30]:
print(a2)

[[ 4  6]
 [87  2]]


In [9]:
a3 = np.array([[[4],[6]],[[87],[2]]])
a3

array([[[ 4],
        [ 6]],

       [[87],
        [ 2]]])

In [40]:
a3.shape

(2, 2, 1)

In [31]:
b = np.array([[4,3,8,9],[2,1,7,13],[19,6,3,9]])
b

array([[ 4,  3,  8,  9],
       [ 2,  1,  7, 13],
       [19,  6,  3,  9]])

In [32]:
b.shape

(3, 4)

In [34]:
# b[0][0] this method will not be used in numpy

In [35]:
b[0,0]

4

In [36]:
b[1,3]

13

In [38]:
b[0,1:]

array([3, 8, 9])

In [39]:
b[1:,1:3]

array([[1, 7],
       [6, 3]])

In [41]:
c = np.array([[[4,40],[8,80],[9,90],[7,70]],[[3,30],[1,10],[2,20],[8,80]],[[11,110],[10,100],[6,60],[1,10]]])
c

array([[[  4,  40],
        [  8,  80],
        [  9,  90],
        [  7,  70]],

       [[  3,  30],
        [  1,  10],
        [  2,  20],
        [  8,  80]],

       [[ 11, 110],
        [ 10, 100],
        [  6,  60],
        [  1,  10]]])

In [42]:
c.shape

(3, 4, 2)

In [43]:
c[0,2,0]

9

In [44]:
c[0,3,1]

70

In [45]:
c[1,:,0]

array([3, 1, 2, 8])

In [48]:
c[1:2,:,0:1]

array([[[3],
        [1],
        [2],
        [8]]])

In [49]:
c[1:2,:,0:1].shape

(1, 4, 1)

In [50]:
c[1:2,:,0]

array([[3, 1, 2, 8]])

In [51]:
c[1:2,:,0].shape

(1, 4)

In [46]:
c[:,0,1]

array([ 40,  30, 110])

In [47]:
c[1:,3,:]

array([[ 8, 80],
       [ 1, 10]])

In [52]:
c[1:,3:4,:]

array([[[ 8, 80]],

       [[ 1, 10]]])

In [53]:
b

array([[ 4,  3,  8,  9],
       [ 2,  1,  7, 13],
       [19,  6,  3,  9]])

In [54]:
b.sum()

84

In [55]:
b.sum(axis=1)

array([24, 23, 37])

In [56]:
b.sum(axis=0)

array([25, 10, 18, 31])

In [ ]:
# sum
# mean
# median
# max
# min
# argmax
# argmin
# std

# reshape
# resize

In [ ]:
# array
# linspace
# arange
# zeros
# ones
# random.rand
# random.randn
# random.randint


# nan